### ISSUE TITLE
some Issues

### ISSUE THREAD

**Issue by hu8813** [gwolf-011235/minishell#71]
hi Gabriel & Sirui,
i tried the program and at first sight, there were following Issues
(didn't test it much, but if i find something, will update here)

Make complaint about:
src/executor_cleanup2.c:27:8: error: variable 'err' set but not used [-Werror,-Wunused-but-set-variable]
        t_err   err;
                ^
1 error generated.

in signal.c , after the line
	struct sigaction	sa;

	`sa = (struct sigaction){0};`  // after adding this there was no valgrind Error about signals

in executor_heredoc:
in func	ft_read_heredoc
`g_status = 0;` // need to set it to 0 at the beginning, otherwise if the old status was saved as 130, it will quit heredoc

when opening ./minishell in ./minishell in ./minishell etc.
signals gets multipled and you can't even enter anything
in the ft_wait_for_babies  need to ignore the signals inside child, before waitpid:

	`signal(SIGQUIT, SIG_IGN);`

	`signal(SIGINT, SIG_IGN);`
	
	and after waitpid, need to add the call to the child signal setter function:
	
	`if (WIFSIGNALED(status))
		ft_signalhandler_child(WTERMSIG(status));`

`nm -u ./minishell` shows forbidden functions: memset, memcpy instead ft_memset or ft_memcpy)

**Comment by gwolf-011235** [comment]
Hey Kaya, 
thanks for checking it out, we really appreciate it! :D

- Right now we are working on branch #50 
There we also fixed some issues which were popping up.

1. Make complain
This will be fixed in branch.

2. Valgrind error in signal.c
I also saw this error. Valgrind complains about sa_mask, because it is not init. But we call sigemptyset() which should init it. If I can't figure out why it complains I'll add your init line!

3. Heredoc
We set g_status to 0 in ft_create_heredoc() right before we call ft_read_heredoc(). Or could this still be an error?

4. Signal no work
This works in branch #50. 
We set sigint and sigquit to a handler, that does nothing, while parsing. When forking the child inherits no handlers so it behaves normally. In wait_for_babies() we check if it exited with signal.
What does this line do: `ft_signalhandler_child(WTERMSIG(status));` - what is signalhanlder_child? :D

5. Forbidden functions
I could not find any in the code. Maybe it shows some functions used by readline?

**Comment by hu8813** [comment]
oh, in the branch everything looks nice ) none of the things i mentioned i could replicate in the branch. really good

well in my case after waitpid i had to call ft_signalhandler_child  kinda function as i ignored the signals in child. but yours do not need anymore

only some errors with "cd" without parameters, 
and some general leaks.  

when i launch minishell and write exit, some leaks. in the main i would better save the input in the struct, so i can free it anywhere needed. also instead of  using exit()  in main i would call a function that checks if everything is freed before exit 

normally the .supp suppression file some people used supressed also some non-readline memory errors, so it was showing all errors in supressed section. BUT yours look like only suppressing the readline, so looks ok i guess.

**Comment by gwolf-011235** [comment]
We now fixed
- cd segfault
- leaks

We let the char input pointer in main because we don't need it anywhere else - we always return back to main to clean up our stuff ;)
